// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n'

export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = {
	/**
	 * Email address
	 */
	'VIEWS_LOGIN_EMAIL_LABEL': string
	/**
	 * We'll never share your email with anyone else.
	 */
	'VIEWS_LOGIN_EMAIL_HELP': string
	/**
	 * Password
	 */
	'VIEWS_LOGIN_PASSWORD': string
	/**
	 * Submit
	 */
	'VIEWS_BUTTON_SUBMIT': string
	/**
	 * Login successful
	 */
	'INFO_LOGIN_SUCCESSFUL': string
	/**
	 * Invalid Credentials
	 */
	'ERROR_INVALID_CREDENTIALS': string
}

export type TranslationFunctions = {
	/**
	 * Email address
	 */
	'VIEWS_LOGIN_EMAIL_LABEL': () => LocalizedString
	/**
	 * We'll never share your email with anyone else.
	 */
	'VIEWS_LOGIN_EMAIL_HELP': () => LocalizedString
	/**
	 * Password
	 */
	'VIEWS_LOGIN_PASSWORD': () => LocalizedString
	/**
	 * Submit
	 */
	'VIEWS_BUTTON_SUBMIT': () => LocalizedString
	/**
	 * Login successful
	 */
	'INFO_LOGIN_SUCCESSFUL': () => LocalizedString
	/**
	 * Invalid Credentials
	 */
	'ERROR_INVALID_CREDENTIALS': () => LocalizedString
}

export type Formatters = {}
